name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK and Gradle
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        ndk: 25.1.8937393 # يمكنك إزالته إذا لم تكن تخطط لاستخدام مكتبات تحتاج NDK

    - name: Build debug APK
      # بدلًا من تشغيل ./gradlew مباشرة، نستخدم 'gradlew' كأمر متاح في المسار
      # وذلك لأن setup-android يضبط بيئة Gradle.
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
